### ISSUE TITLE
Pushing image fails with auth issue

### ISSUE THREAD

**Issue by rberrelleza** [LucasRoesler/openfaas-action#3]
I have the following action configured:

```
name: FaaS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build function
      uses: LucasRoesler/openfaas-action/build@v0.1.0
      with:
        tag: "latest"
        path: "api.yml"

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Push function
      uses: LucasRoesler/openfaas-action/push@v0.1.0
      with:
        tag: "latest"
        path: "api.yml"
```

Building the image works fine, but pushing it to the registry fails with an auth error:

```
denied: requested access to the resource is denied
```

You can see a repro here:  https://github.com/rberrelleza/faas-actions/runs/710408402?check_suite_focus=true

I also tried running docker login directly, but got the same error: https://github.com/rberrelleza/faas-actions/runs/710482839?check_suite_focus=true
